version: '3'

networks:
  gitea:
    driver: bridge

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    networks:
      - gitea

  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "8081:3000" # Node.js app runs on port 3000 inside the container
    networks:
      - gitea

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000 # Replace with the UID found from previous command output
      - USER_GID=1000 # Replace with the GID found from previous command output
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - gitea
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=gitea
       - MYSQL_USER=gitea
       - MYSQL_PASSWORD=gitea
       - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  jenkins_data:
    driver: local
  gitea-data:
    driver: local
  mysql-data:
    driver: local
